# Generated by Django 4.1.2 on 2022-10-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='photos/')),
                ('PRDName', models.CharField(max_length=30)),
                ('PRDQuantity', models.DecimalField(
                    decimal_places=2, max_digits=5)),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PRDCategory', models.CharField(choices=[
                 ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables')], max_length=15)),
            ],
        ),
    ]
