# Generated by Django 4.1.2 on 2022-10-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_prdimage_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Image'),
        ),
    ]
