# Generated by Django 4.1.2 on 2022-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_prdimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDQuantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Quantity'),
        ),
    ]
