# Generated by Django 4.1.2 on 2022-10-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_prdprice_alter_product_prdquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Onions', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Potatos', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Carrots', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
    ]
