# Generated by Django 4.1.2 on 2022-10-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='Carrots',
            new_name='carrots',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='Onions',
            new_name='onions',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='Potatos',
            new_name='potatos',
        ),
    ]
